Ed-Fi-Alliance-OSS/AdminAPI-2.x

Application/EdFi.Ods.AdminApi.DBTests/Database/CommandTests/EditApplicationCommandTests.cs, Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E.postman_collection.json, Application/EdFi.Ods.AdminApi/Features/Applications/ApplicationModel.cs, Application/EdFi.Ods.AdminApi/Infrastructure/AutoMapper/AdminApiMappingProfile.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Extensions/AdminModelExtensions.cs, Application/EdFi.Ods.AdminApi/Infrastructure/WebApplicationBuilderExtensions.cs
Return vendor and profile ID in applications endpoints
=> [ADMINAPI-311] Return vendor and profile ID in /applications endpoints

Application/EdFi.Ods.AdminApi/Docker/dev/adminapi-test-seeddata.sql, Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E.postman_collection.json, Application/EdFi.Ods.AdminApi/dbadmin.Dockerfile
@CSR2017 @jasonh-edfi 
this is the fix for the execution of E2E in adminapi 2.0
=> [ADMINAPI-328] Fix E2E execution

Application/EdFi.Ods.AdminApi/EdFi.Ods.AdminApi.csproj, Application/EdFi.Ods.AdminApi/EdFi.Ods.AdminApi.nuspec
@jpardogrowthaccelerationpartners @lchavarriaga @jagudelo-gap 
Please help review and merge the changes.
Thanks
=> [ADMINAPI-332] Include database scripts artifacts as part of package - part 1

Application/EdFi.Ods.AdminApi/Docker/DB-Admin/pgsql/Dockerfile, Application/EdFi.Ods.AdminApi/Docker/DB-Admin/pgsql/run-adminapi-migrations.sh, Application/EdFi.Ods.AdminApi/dbadmin.Dockerfile, Application/EdFi.Ods.AdminApi/mssql.Dockerfile, Application/EdFi.Ods.AdminApi/pgsql.Dockerfile
@jagudelo-gap @lchavarriaga 
Updated docker files to retrieve the AdminApi related db scripts files from Admin API package.
Updating the version to pre-release version temporarily for testing. Will be updated to release version during the release.
=> [ADMINAPI-332] Update the docker files to get the db script files from Admin API package

.github/workflows/on-prerelease.yml, .github/workflows/on-pullrequest-dockerfile.yml, Docker/api-mssql.Dockerfile, Docker/api-pgsql.Dockerfile, Docker/dev.Dockerfile
@stephenfuqua @jpardogrowthaccelerationpartners @jasonh-edfi 
Please help review and merge the changes.
Please help with setting the following secrets and variables:
**Variables:**
Variable Name	:  Variable Value
IMAGE_NAME :  edfialliance/ods-admin-api
DATABASE_IMAGE_NAME : edfialliance/ods-admin-api-db
DOCKER_USERNAME: edfialliance user name>
**Secrets:**
DOCKER_HUB_TOKEN: edfialliance docker hub token
Thanks
=> [ADMINAPI-346] Automate the Docker image building for the Ed-Fi ODS Admin API

Application/EdFi.Ods.AdminApi.DBTests/ClaimSetEditorTests/GetResourcesByClaimSetIdQueryTests.cs, Application/EdFi.Ods.AdminApi.DBTests/ClaimSetEditorTests/OverrideDefaultAuthorizationStrategyCommandTests.cs, Application/EdFi.Ods.AdminApi.DBTests/EdFi.Ods.AdminApi.DBTests.csproj, Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E 2.0 - ClaimSets.postman_collection.json, Application/EdFi.Ods.AdminApi/EdFi.Ods.AdminApi.csproj, Application/EdFi.Ods.AdminApi/Features/ClaimSets/ClaimSetModel.cs, Application/EdFi.Ods.AdminApi/Features/ClaimSets/ResourceClaimValidator.cs, Application/EdFi.Ods.AdminApi/Features/ClaimSets/ResourceClaims/EditAuthStrategy.cs, Application/EdFi.Ods.AdminApi/Infrastructure/AutoMapper/AdminApiMappingProfile.cs, Application/EdFi.Ods.AdminApi/Infrastructure/AutoMapper/Converters.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/AddOrEditResourcesOnClaimSetCommand.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/AuthStrategyResolver.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/AuthorizationStrategy.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/ClaimSetResourceClaimActionAuthStrategies.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/GetAllAuthorizationStrategiesQuery.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/GetResourcesByClaimSetIdQuery.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/OverrideDefaultAuthorizationStrategyCommand.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Services/ClaimSetEditor/ResourceClaim.cs
@jagudelo-gap @lchavarriaga 
Please help review and merge the changes.
Thanks
=> [ADMINAPI-631] Claimset - Implement multiple auth strategies support

Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E 2.0 - Vendors.postman_collection.json, Application/EdFi.Ods.AdminApi/appsettings.Docker.json
@CSR2017 @jasonh-edfi 
Could you review and merge this PR.
Changes:
- Adding offset and sizeLimit on appsettings docker template
- test for vendor with associated applications
=> [ADMINAPI-698] Add missing endpoint tests and additional configuration

Application/EdFi.Ods.AdminApi/Infrastructure/Security/SecurityExtensions.cs
https://tracker.ed-fi.org/browse/ADMINAPI-763
=> [ADMINAPI-763] Set access token life time

Installer.AdminApi/install.ps1
=> [ADMINAPI-955] Update version on install.ps1

.github/workflows/on-prerelease.yml, .github/workflows/on-pullrequest-dockerfile.yml
Files updated:
- on-prerelease.yml
- on-pullrequest-dockerfile.yml
=>  [ADMINAPI-992] Update GitHub Actions in AdminApi-2.x to Use Latest  -  Updat of pending actions

.github/workflows/on-pullrequest.yml
[ADMINAPI-1000] Missing Event File Upload for Admin API 2.x
Adding the job to the CI workflow.
=> [ADMINAPI-1000] Missing Event File Upload for Admin API 2.x

Application/EdFi.Ods.AdminApi.DBTests/EdFi.Ods.AdminApi.DBTests.csproj, Application/EdFi.Ods.AdminApi.UnitTests/EdFi.Ods.AdminApi.UnitTests.csproj, Application/EdFi.Ods.AdminApi/EdFi.Ods.AdminApi.csproj, Application/EdFi.Ods.AdminApi/appsettings.json
Notice this message on EdFi.Ods.AdminAPI
Then remove unused dependencies:
=> [ADMINAPI-998] Remove deps.json file from Docker image

.github/workflows/after-pullrequest.yml, .github/workflows/on-prerelease.yml
Rollback content write permissions, Add read at top on after-pull request
=> [ADMINAPI-993] Permissions improvements

.github/workflows/on-prerelease.yml
Put back contents:write permissions on-prerelease
=> [ADMINAPI-993] Put back contents:write permissions on-prerelease

BuildDockerDevelopment.ps1, Installer.AdminApi/install.ps1
Update installer for AdminApi 2.2.0
=> [ADMINAPI-984] Update installer for 2.2.0 release

build.ps1
Now that we are treating warnings as errors, there are some warnings preventing the packaging steps.
=> [ADMINAPI-984] Update the NoWarn parameter for nuget

Application/EdFi.Ods.AdminApi.DBTests/Database/CommandTests/DeleteApplicationCommandTests.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Database/Commands/DeleteApplicationCommand.cs
- Delete ApiClient when the Application is deleted.
=> [ADMINAPI-1024]  Vendor delete issue in AdminAPI 2.x

Application/EdFi.Ods.AdminApi/Infrastructure/Database/Commands/DeleteVendorCommand.cs
Update Delete to delete vendors that failed with the previous version
=> [ADMINAPI-1024] Vendor delete issue in AdminAPI 2.x

Application/EdFi.Ods.AdminApi.DBTests/Database/CommandTests/AddApplicationCommandTests.cs, Application/EdFi.Ods.AdminApi.DBTests/Database/CommandTests/EditApplicationCommandTests.cs, Application/EdFi.Ods.AdminApi/Features/Applications/AddApplication.cs, Application/EdFi.Ods.AdminApi/Features/Applications/EditApplication.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Database/Commands/AddApplicationCommand.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Database/Commands/EditApplicationCommand.cs
- Update EducationOrganizationId from int to long
=> [ADMINAPI-1023] Admin Api 2.1.0 and 2.2.0 Unable to create applications with big int ids.

Application/EdFi.Ods.AdminApi.DBTests/Database/CommandTests/AddApplicationCommandTests.cs, Application/EdFi.Ods.AdminApi.DBTests/Database/CommandTests/EditApplicationCommandTests.cs, Application/EdFi.Ods.AdminApi/Features/Applications/AddApplication.cs, Application/EdFi.Ods.AdminApi/Helpers/AppSettings.cs, Application/EdFi.Ods.AdminApi/Infrastructure/AdminApiEndpointBuilder.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Database/Commands/AddApplicationCommand.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Database/Queries/ValidateApplicationExistsQuery.cs, Application/EdFi.Ods.AdminApi/appsettings.json, Docker/Compose/pgsql/MultiTenant/compose-build-binaries-multi-tenant.yml, Docker/Compose/pgsql/MultiTenant/compose-build-dev-multi-tenant.yml, Docker/Compose/pgsql/SingleTenant/compose-build-binaries.yml, Docker/Settings/mssql/appsettings.template.json, Docker/Settings/mssql/env.example, Docker/Settings/pgsql/appsettings.template.json, Docker/Settings/pgsql/env.example
- Add validation to get duplicated applications
- Add Flag to prevent duplicated applications
- Add test
=> [ADMINAPI-321]  Admin API allows duplicate Applications

Application/EdFi.Ods.AdminApi/Features/RequestLoggingMiddleware.cs
Show AdminApiException message if a StatusCode is defined.
=>  ADMINAPI-321 Admin API allows duplicate Applications

Application/EdFi.Ods.AdminApi.UnitTests/Features/SortableListTests.cs, Application/EdFi.Ods.AdminApi/Features/Actions/ReadActions.cs, Application/EdFi.Ods.AdminApi/Features/Applications/ReadApplication.cs, Application/EdFi.Ods.AdminApi/Features/ClaimSets/ReadClaimSets.cs, Application/EdFi.Ods.AdminApi/Features/OdsInstances/ReadOdsInstance.cs, Application/EdFi.Ods.AdminApi/Features/Profiles/ReadProfile.cs, Application/EdFi.Ods.AdminApi/Features/ResourceClaims/ReadResourceClaims.cs, Application/EdFi.Ods.AdminApi/Features/SortableList.cs, Application/EdFi.Ods.AdminApi/Features/SortingDirection.cs, Application/EdFi.Ods.AdminApi/Features/Vendors/ReadVendor.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Database/Queries/GetVendorsQuery.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Documentation/SwaggerDefaultParameterFilter.cs, Application/EdFi.Ods.AdminApi/Infrastructure/Extensions/QueryExtensions.cs, docs/swagger.yaml, docs/yaml-to-md/adminapi2x.md
* Replace sortBy by orderBy
* Replace descendingSort by direction to use Asc or Desc instead of the boolean
* Update documentation
=> ADMINAPI-1028 Admin API to implement sorting and filtering on endpoints with "direction" and "orderBy"

Application/EdFi.Ods.AdminApi/Features/FeatureConstants.cs
Fix constant value to default sort
=> ADMINAPI-1028 Admin API to implement sorting

.github/workflows/api-e2e-pgsql-multitenant.yml, .github/workflows/api-e2e-pgsql-singletenant.yml, Application/EdFi.Ods.AdminApi.DBTests/EdFi.Ods.AdminApi.DBTests.csproj, Application/EdFi.Ods.AdminApi.DBTests/PlatformSecurityContextTestBase.cs, Application/EdFi.Ods.AdminApi.UnitTests/EdFi.Ods.AdminApi.UnitTests.csproj, Application/EdFi.Ods.AdminApi/EdFi.Ods.AdminApi.csproj, Docker/Settings/DB-Admin/pgsql/Dockerfile, Docker/dbadmin.Dockerfile
- Update nuget packages
- Add version to docker files and npm packages.
=> ADMINAPI-1036 Resolve high and critical flags in Code Scanning for Admin API 2.3 release

docs/migration-guide-docker.md
Update temp folder path and instructions
=> AdminApi-1045 Migration Guide

BuildDockerDevelopment.ps1, Installer.AdminApi/install.ps1
Update installer for 2.3.0 release
=> [ADMINAPI-1034] - Release Admin API 2.2.1

Application/EdFi.Ods.AdminApi/AdminConsole/Configurations/AdminConsoleExtension.cs
Fix multitenant initial configuration
=> AC-116 Create Health Check Credentials for Instances on Startup (FIX)

Application/EdFi.Ods.AdminApi/appsettings.Docker.json
Add parameters to appsettings.docker.json
=> AC-116 Create Health Check Credentials for Instances on Startup

.github/workflows/after-pullrequest.yml, .github/workflows/on-prerelease.yml, .github/workflows/on-release.yml, .github/workflows/openapi-md.yml
The only permission that I cannot fix is ​​the provenance-create permission when uploading the assets because if I change the permission for another one, the step continues asking for the same rule that is vulnerable.
=> [ADMINAPI-1139] Fix permissions workflows

Application/EdFi.Ods.AdminApi/appsettings.Docker.json, Application/EdFi.Ods.AdminApi/appsettings.Docker.mssql.json, Application/EdFi.Ods.AdminApi/appsettings.json, Docker/Settings/mssql/appsettings.template.json, Docker/Settings/pgsql/appsettings.template.json
- Remove comments
- Synchronize Application and Docker AppSettings
=> ADMINAPI-1165 Update appsettings for Docker (AdminConsole)

.github/workflows/on-prerelease.yml
=> ADMINAPI-1165 Update flow settings

.gitignore, .vscode/extensions.json, .vscode/settings.json, Application/Ed-Fi-ODS-AdminApi.sln, Application/EdFi.Ods.AdminApi.AdminConsole.UnitTests/EdFi.Ods.AdminApi.AdminConsole.UnitTests.csproj, Application/EdFi.Ods.AdminApi.AdminConsole.UnitTests/Infrastructure/DataAccess/Models/InstanceTest.cs, Application/EdFi.Ods.AdminApi.AdminConsole/Infrastructure/DataAccess/Models/Instance.cs, Application/EdFi.Ods.AdminApi.AdminConsole/Infrastructure/Services/Instances/Commands/AddInstanceCommand.cs, Application/EdFi.Ods.AdminApi.Common.UnitTests/EdFi.Ods.AdminApi.Common.UnitTests.csproj, Application/EdFi.Ods.AdminApi.Common.UnitTests/Features/AdminApiErrorTest.cs, Application/EdFi.Ods.AdminApi.Common/Features/AdminApiError.cs, Application/EdFi.Ods.AdminApi.DBTests/EdFi.Ods.AdminApi.DBTests.csproj, Application/EdFi.Ods.AdminApi.UnitTests/EdFi.Ods.AdminApi.UnitTests.csproj, Application/EdFi.Ods.AdminConsole.DBTests/EdFi.Ods.AdminConsole.DBTests.csproj, build.ps1, docs/developer.md
Please review the developers notes for instructions on running the code coverage analysis.
=> [ADMINAPI-1178] Add code coverage reporting to build script; expand unit test coverage

Docker/KeyCloak/realm-and-users.json
Update sample data to use same data as AdminConsole repo
=> AC-161 Update keycloak sample data

Application/EdFi.Ods.AdminApi.AdminConsole/Infrastructure/Services/Instances/Commands/RenameFailedInstanceCommand.cs, Application/EdFi.Ods.AdminApi.AdminConsole/Infrastructure/Services/Instances/Commands/RenameInstanceCommand.cs, Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E 2.0 - AdminConsole - Instances.postman_collection.json, Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E 2.0 - AdminConsole - OdsInstances.postman_collection.json
Add tests (delete, delete_failed, rename, rename_failed)
Update rename methods to change status codes.
=> ADMINAPI-1177 e2e tests to cover implementation on /adminconsole/instances

Application/EdFi.Ods.AdminApi/appsettings.Development.json, Application/EdFi.Ods.AdminApi/appsettings.Docker.json, Application/EdFi.Ods.AdminApi/appsettings.json, build.ps1
Add key Authentication:Authority
Update build.ps1
=> ADMINAPI-1195 Add Authority key to appSettings

Application/EdFi.Ods.AdminApi/Features/RequestLoggingMiddleware.cs
This is a fix for the error shown on [this](https://edfi.atlassian.net/browse/ADMINAPI-1208?focusedCommentId=64536) comment.
=> [ADMINAPI-1208] - Error fix - Cannot access closed stream.

docs/design/ADMINAPI-1284-adminconsole-definition-removal.md
This document outlines the findings from the analysis phase (Phase 1) of the ticket ADM### Proposed Endpoint Structure
| Current Endpoint | Proposed Endpoint | Purpose |
|------------------|-------------------|---------|
| `/adminconsole/tenants` | `/v2/tenants` | List all tenants |
| `/adminconsole/tenants/{tenantId}` | `/v2/tenants/{tenantId}` | Get tenant details |
| `/adminconsole/odsInstances/{id}` | `/v2/odsInstances/{id}/metadata` | Get instance details |
The following `/adminconsole` endpoints have been identified in the codebase:
| Endpoint | HTTP Method | Purpose |
|----------|-------------|---------|
| `/tenants` | GET | List all tenants |
| `/tenants/{tenantId}` | GET | Get tenant details by ID |
| `/odsInstances` | GET | List all ODS instances |
| `/odsInstances/{id}` | GET | …
=> [ADMINAPI-1284] Add design document for Redesign the API definitions from /adminconsole
